# TOML

title = "Vcfanno configuration file"

[[annotation]]
file="grch38_gnomad_reformated_-r3.1.2-.vcf.gz"
fields = ["AF", "AF_popmax"]
ops=["self", "self"]
names=["GNOMADAF", "GNOMADAF_popmax"]

[[annotation]]
file="grch38_gnomad_genomes_mt_-r3.1-.vcf.gz"
fields = ["AF_hom", "AF_het", "mitotip_score", "mitotip_trna_prediction"]
ops=["self", "self", "self", "self"]
names=["MTAF_hom", "MTAF_het", "mitotip_score", "mitotip_trna_prediction"]
