# TOML

title = "Vcfanno configuration file" 

[functions]
file="vcfanno_functions_-v1.0-.lua"

[[annotation]]
file="grch38_gnomad_reformated_-r3.1.1-.vcf.gz"
fields = ["AF", "AF_popmax"]
ops=["self", "self"]
names=["GNOMADAF", "GNOMADAF_popmax"]

[[annotation]]
file="grch38_swegen_frequencies_fixploidy_-20190204-.vcf.gz"
fields = ["AF", "AC_Hom", "AC_Het", "AC_Hemi"]
ops=["self", "self", "self", "self"]
names=["SWEGENAF", "SWEGENAAC_Hom", "SWEGENAAC_Het", "SWEGENAAC_Hemi"]

[[annotation]]
file="grch38_gnomad_genomes_mt_-r3.1-.vcf.gz"
fields = ["AF_hom", "AF_het", "mitotip_score", "mitotip_trna_prediction"]
ops=["self", "self", "self", "self"]
names=["MTAF_hom", "MTAF_hom", "mitotip_score", "mitotip_trna_prediction"]

[[annotation]]
file="grch38_cadd_whole_genome_snvs_-v1.6-.tsv.gz"
names=["CADD"]
ops=["mean"]
columns=[6]
