# TOML

title = "Vcfanno configuration file" 

[[annotation]]
file="grch37_gnomad_reformated_-r2.1.1-.vcf.gz"
fields = ["AF", "AF_popmax"]
ops=["self", "self"]
names=["GNOMADAF", "GNOMADAF_popmax"]

[[annotation]]
file="grch37_anon-swegen_str_nsphs_-1000samples-.vcf.gz"
fields = ["AF", "AC_Hom", "AC_Het", "AC_Hemi"]
ops=["self", "self", "self", "self"]
names=["SWEGENAF", "SWEGENAC_Hom", "SWEGENAC_Het", "SWEGENAC_Hemi"]

[[annotation]]
file="grch37_loqusdb_snv_indel_-2019-11-04-.vcf.gz"
fields = ["Obs", "Hom"]
ops=["self", "self"]
names=["Obs", "Hom"]

[[annotation]]
file="grch37_genbank_haplogroup_-2015-08-01-.vcf.gz"
fields = ["MTAF"]
ops=["self"]
names=["MTAF"]
